### PR TITLE
Fixed BatchNorm not de/serialising correctly

### LINKED ISSUE #166: Default serialisation fails for `BatchNorm`.
Hi,

The defaut serialisation fails when a model with `BatchNorm` is serialised. A small test script executed on `dev` branch.

```python

def test_serialise_bn(getkey):
    net = eqx.nn.Sequential(
        [
            eqx.experimental.BatchNorm(3, axis_name="batch"),
        ]
    )

    eqx.tree_serialise_leaves('/tmp/net.eqx', net)

    assert True
```
 
with the error
```console
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../equinox/serialisation.py:183: in tree_serialise_leaves
    jtu.tree_map(_serialise, filter_spec, pytree)
../../../miniconda3/envs/equinox/lib/python3.8/site-packages/jax/_src/tree_util.py:201: in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
../../../miniconda3/envs/equinox/lib/python3.8/site-packages/jax/_src/tree_util.py:201: in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
../equinox/serialisation.py:181: in _serialise
    jtu.tree_map(__serialise, x, is_leaf=is_leaf)
../../../miniconda3/envs/equinox/lib/python3.8/site-packages/jax/_src/tree_util.py:201: in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
../../../miniconda3/envs/equinox/lib/python3.8/site-packages/jax/_src/tree_util.py:201: in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
../equinox/serialisation.py:179: in __serialise
    spec(f, y)
../equinox/serialisation.py:50: in default_serialise_filter_spec
    value, _, _ = x.unsafe_get()
../equinox/experimental/stateful.py:112: in unsafe_get
    return _state_cache[self._obj]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <WeakKeyDictionary at 0x7fc6deff8d90>
key = <equinox.experimental.stateful._IndexObj object at 0x7fc6deec12b0>

    def __getitem__(self, key):
>       return self.data[ref(key)]
E       KeyError: <weakref at 0x7fc736f7e590; to '_IndexObj' at 0x7fc6deec12b0>

../../../miniconda3/envs/equinox/lib/python3.8/weakref.py:383: KeyError
```

### PR DESCRIPTION
**Pull request by patrick-kidger**
Fixes #166.

### CODE REVIEW

**Comment by paganpasta** [comment]
Hi @patrick-kidger 

Not sure if you had the chance to see the latest issue w.r.t this fix: https://github.com/patrick-kidger/equinox/issues/166#issuecomment-1219280488
Linking here for better visibility.

**Comment by patrick-kidger** [comment]
Heyhey -- yep, I've seen this and just haven't had time to dig into this yet.

**Comment by patrick-kidger** [comment]
@paganpasta Okay, I think this should be fixed now! The mistake turned out to be pretty deep into the voodoo magic that makes stateful operations work. (I look forward to the day that proper stateful operations become part of JAX core.)

I've checked that this resolves the particular repro in [#166 (comment)](https://github.com/patrick-kidger/equinox/issues/166#issuecomment-1219280488). Can you confirm that this also solves your downstream use cases? If so I'll merge this PR.

**Comment by paganpasta** [comment]
@patrick-kidger Thanks for the fix. It works for other use-cases I have tried. Looking forward to the new release!

**Comment by paganpasta** [comment]
Hi @patrick-kidger, trying to understand the behaviour when generating adversarial samples.

The current workflow is:
1. Define a model
2. Load saved weights (from pytorch).
3. **Set the model to inference mode**(?)
4. Compute gradient w.r.t input

As I understand, setting to inference will not work because the underlying state is not set (checked, getting the same error as before). However, not setting the model in inference mode will compute stats during the forward pass and change what the network produces as the final output (slightly different forward results with and without inference).

Is there a workaround for this? Or perhaps it's a bug?

**Comment by patrick-kidger** [comment]
Hmm, that sounds like a variation on the same bug. Stateful operations handle inference mode and training mode differently for efficiency reasons.

Can you produce a MWE?

**Comment by paganpasta** [comment]
Sure, I made some changes to the previous MWE. Needs to run twice. Once with `SAVE=True` and then with `False`.

```python
import jax
import jax.numpy as jnp
import jax.random as jrandom
import optax

import numpy as np
import equinox as eqx

SAVE = True


@eqx.filter_value_and_grad
def compute_loss_adv(x, model, y, keys):
    logits = jax.vmap(model, axis_name=('batch'))(x, key=keys)
    one_hot_actual = jax.nn.one_hot(y, num_classes=5)
    return optax.softmax_cross_entropy(logits, one_hot_actual).mean()


@eqx.filter_value_and_grad
def compute_loss(model, x, y, keys):
    logits = jax.vmap(model, axis_name=('batch'))(x, key=keys)
    one_hot_actual = jax.nn.one_hot(y, num_classes=5)
    return optax.softmax_cross_entropy(logits, one_hot_actual).mean()


@eqx.filter_jit
def make_step(model, x, y, keys, optimizer, opt_state):
    loss, grads = compute_loss(model, x, y, keys)
    updates, opt_state = optimizer.update(grads, opt_state)
    model = eqx.apply_updates(model, updates)
    return loss, model, opt_state


net = eqx.nn.Sequential(
    [
        eqx.nn.Linear(3, 5, key=jrandom.PRNGKey(0)),
        eqx.experimental.BatchNorm(5, axis_name='batch')
    ]
)

x = jnp.asarray(np.random.rand(10, 3))
y = jnp.asarray(np.random.randint(0, 9, 10))
key = jrandom.split(jrandom.PRNGKey(0), 10)
if SAVE:
    optimizer = optax.adam(learning_rate=0.1)
    opt_state = optimizer.init(eqx.filter(net, eqx.is_array))
    _, net, _ = make_step(net, x, y, key, optimizer, opt_state)
    eqx.tree_serialise_leaves('/tmp/net.eqx', net)
else:
    net = eqx.tree_deserialise_leaves('/tmp/net.eqx', net)
    net = eqx.tree_inference(net, True)
    # normal forward works
    output = jax.vmap(net, axis_name='batch')(x)
    print(output.shape)
    # grad w.r.t input fails
    loss, grads = compute_loss_adv(x, net, y, key)


```

**Comment by patrick-kidger** [comment]
Right, I had just missed applying the same fix to the inference-mode branch of `BatchNorm`.

Once again -- let me know if this seems to have fixed all your downstream use cases, and if so I'll merge this.

**Comment by paganpasta** [comment]
This case seems to be fixed as well! 
I currently don't have any other uses readily available to test. Hopefully, all has been taken care of :D

**Pull request merged**
