### PR TITLE
Fix MyPy's view of _ModuleMeta

### PR DESCRIPTION
**Pull request by NeilGirdhar**

### CODE REVIEW

**Comment by patrick-kidger** [comment]
The downside of this approach is that it means we lose type-checking within the definition of `_ModuleMeta` itself.

Would something like the following work?
```python
# As today, but the name has an additional underscore
class __ModuleMeta(ABCMeta):
    ...

if TYPE_CHECKING:
    class _ModuleMeta: ...  # as today
else:
    _ModuleMeta = __ModuleMeta
```
?

**Comment by NeilGirdhar** [comment]
Yup, that's a good idea!

**Comment by patrick-kidger** [comment]
Looks like tests are failing (due to something to do with name mangling). Other than that, LGTM!

**Comment by NeilGirdhar** [comment]
Fixes #820

**Comment by patrick-kidger** [comment]
Wonderful stuff. LGTM, and merged!

**Pull request merged**
