### PR TITLE
Add example of serialisation of hyperparameters (#370)

### PR DESCRIPTION
**Pull request by bytbox**
A first draft, I guess. As discussed here: https://github.com/patrick-kidger/equinox/issues/370#issuecomment-1564513099. I tried to clean things up a bit, and avoid encouraging bad practices like overuse of pickle.

One warning: I couldn't get the pre-commit hooks to run correctly, so I just disabled them. I'm assuming they don't operate on ipynb files! If they do, let me know and I'll go back and try harder.

### CODE REVIEW

**Review by patrick-kidger — COMMENTED** [review]
Thanks for the contrbution!

The pre-commit hooks do run on `.ipynb` files. What kind of issue are you getting with them?

Reading over the example, it looks really good! The trick with `\n` is pretty neat.

Typo: `make(key=jr.PRNGKey(0), **params)` inside `load` should have a `model = ...`.

Nit: consistently used "Equinox" over "equinox" or "`equinox`".

Suggestion: the approach you're using here relies on the hyperparameters themselves being serialisable. It'd be worth explicitly mentioning that this is a requirement.

**Comment by bytbox** [comment]
I added a commit, with everything fixed. I don't remember what error I was getting installing the pre-commit hooks, but I think it was related to using a virtual environment. Just installing everything globally worked fine.

Thanks!

**Comment by bytbox** [comment]
Done and pushed!

**Comment by patrick-kidger** [comment]
Marvellous -- merged! Thank you for contributing.

**Pull request merged**
