### PR TITLE
Fix rmsnorm

### PR DESCRIPTION
**Pull request by AakashKumarNain**
The norm calculations should always be done with at least `fp32` dtype, and then the result should be casted back to the original dtype

### CODE REVIEW

**Comment by lockwo** [comment]
Won't this downcast if we are using float64?

**Comment by AakashKumarNain** [comment]
I can fix that. Thanks for pointing it out

**Comment by patrick-kidger** [comment]
I think this should be done using `jnp.result_type`, not with an explicit blocklist.

See how attention handles the same thing: https://github.com/patrick-kidger/equinox/blob/62304f5c5d1aaf0e45fcc9c27ba6a54f0e358b4e/equinox/nn/_attention.py#L36

**Comment by AakashKumarNain** [comment]
> not with an explicit blocklist.

@patrick-kidger can you please elaborate a bit more on this?

**Comment by patrick-kidger** [comment]
Right now you're explicitly checking against a list of dtypes. This is (a) not necessarily forward-compatible with any changes to the dtype system (consider a hypothetical `float128` being added), and (b) will already do the wrong thing for e.g. complex dtypes.

**Comment by AakashKumarNain** [comment]
Makes sense. Thanks for the suggestion. Let me change that accordingly

**Comment by patrick-kidger** [comment]
LGTM -- merged! Thank you for the fix.

**Pull request merged**
